# Importación de Librerías

## Importación de Librerías

### Importación de Librerías

Importación de Librerías

In [12]:
from sklearn.datasets import load_iris

In [15]:
import pandas as pd

# Carga del dataset iris

In [18]:
iris = load_iris()

In [20]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [22]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [24]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Creación de un DataFrame de Pandas

In [35]:
df = pd.DataFrame(data=iris.data, columns=iris.feature_names) 

df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

# Agregamos la columna especie (variable Categórica)

In [40]:
df['sepal length (cm)'] # Si quiero observar una columna ya creada

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64

In [42]:
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names) # Creo una columna nueva

In [44]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

# Contar la cantidad y calcular la frecuencia porcentual

## Ejemplo con cada especie

In [48]:
species_count = df['species'].value_counts()

species_count

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [50]:
# Calculamos la frecuencia porcentual de cada especie:

species_porcent = df['species'].value_counts(normalize=True)

species_porcent

species
setosa        0.333333
versicolor    0.333333
virginica     0.333333
Name: proportion, dtype: float64

In [52]:
# Calculamos la frecuencia porcentual de cada especie * 100:

species_porcent = df['species'].value_counts(normalize=True) * 100

species_porcent

species
setosa        33.333333
versicolor    33.333333
virginica     33.333333
Name: proportion, dtype: float64

## Ejemplo con un vector

In [55]:
# Contamos las frecuencias de los valores de un vector

vec = pd.Series([1,1,1,0,0,3,3,3,2])

In [59]:
vec_counts = vec.value_counts()

vec_counts

1    3
3    3
0    2
2    1
Name: count, dtype: int64

In [61]:
# Calculamos las frecuencias porcentuales del vector:

vec_porcent = vec.value_counts(normalize=True)

vec_porcent

1    0.333333
3    0.333333
0    0.222222
2    0.111111
Name: proportion, dtype: float64

# Medidas de Tendencia Central

# Moda

## Ejemplo con un vector

In [65]:
vec = pd.Series([1,1,1,0,0,3,3,3,2])
mode_vec = vec.mode()

mode_vec

0    1
1    3
dtype: int64

In [67]:
vec_2 = pd.Series([1,1,1,1,0,0,3,3,3,2])
mode_vec_2 = vec_2.mode()

mode_vec_2

0    1
dtype: int64

In [69]:
type(mode_vec)

pandas.core.series.Series

### Podemos pasar la Serie a un arreglo de Numpy:

In [75]:
vec = pd.Series([1,1,1,0,0,3,3,3,2])
mode_vec = vec.mode().values

mode_vec

array([1, 3], dtype=int64)

In [77]:
type(mode_vec)

numpy.ndarray

## Ejemplo con una columna del dataset Iris

In [82]:
mode_sepal_length = df['sepal length (cm)'].mode()

mode_sepal_length

0    5.0
Name: sepal length (cm), dtype: float64

## Media

In [89]:
mean_sepal_length = df['sepal length (cm)'].mean()

mean_sepal_length

5.843333333333334

### Ejemplo con un vector

In [94]:
# Importamos la librería Numpy
import numpy as np

In [96]:
# Generamos un vector aleatorio con media 20 y desviación estándar 10

vec = np.random.normal(20, 10, 10) # El 3er atributo indica la cantidad de elementos del vector

np.mean(vec) # Este es el método para calcular la media utilizando Numpy

22.18838154810072

In [98]:
# Generamos un vector aleatorio que representará un outlier con media 300 y desviación estándar 100

vec_2 = np.random.normal(300, 100, 1)

In [100]:
# Añadimos el valor atípico (ruido/outlier) al 1er vector creado

vec_ruid = np.append(vec, vec_2)

In [102]:
np.mean(vec_ruid)

56.778202721667554

## Media Truncada

In [107]:
from scipy.stats import trim_mean # importamos el método trim_mean

### Ejemplo con un vector

In [111]:
# A través de la media truncada no considero el 10% (en este caso) superior e inferior del conjunto de datos analizados

mean_trimmed_vec = trim_mean(vec, 0.1)
mean_trimmed_vec_ruid = trim_mean(vec_ruid, 0.1)

print(mean_trimmed_vec)
print(mean_trimmed_vec_ruid) # Podemos observar en su salida que es mucho más robusto ante los outliers

22.04987323179892
23.46806593914755


### Ejemplo con una columna del dataset Iris

In [119]:
mean_trimmed_sepal_length = trim_mean(df['sepal length (cm)'], 0.1)

mean_trimmed_sepal_length

5.8083333333333345

## Mediana

### Ejemplo para un vector

In [128]:
median_vec = np.median(vec)
median_vec_ruid = np.median(vec_ruid)

print(median_vec)
print(median_vec_ruid) # Podemos observar en su salida que es mucho más robusto ante los outliers que la media

25.486539396320175
26.50371662631796


### Ejemplo con una columna del dataset Iris

In [132]:
median_sepal_length = df['sepal length (cm)'].median()

median_sepal_length

5.8